[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tiny_spl = "GtmXMfBWq3ku8Y2zWuPzGPnU4PYqykvJgBsE4St41Wuv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nelson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
